### ISSUE TITLE
librato-python-web is too intrusive and hard to deploy

### ISSUE THREAD

**Issue by vslavik** [librato/librato-python-web#35]
The tricks librato-python-web is doing to make it work automagically, without any work, are nice in theory, but actually become a serious obstacle when using this in practice in anything other than what you expected.

For one thing, you assume the server process is self-hosted and launched through a script. That's not a very practical deployment method these days, a combination of nginx + uWSGI with its Python module is much better. Making that work involves reverse-engineering the launcher script and figuring out that I need to launch a helper statsd server and set some environment variables:
```
env = LIBRATO_INSTRUMENT_PYTHON=1
env = LIBRATO_INSTRUMENTATION_PORT=8142
attach-daemon = /srv/myapp/venv/bin/librato-statsd-server
```

OK, but this will also affect the non-WSGI scripts running as part of the same uWSGI app, e.g. Celery process. That's because there's *another bit of magic*, the automatic import of `librato_python_web.instrumentor` from the `.pth` file. As this happens very early, I have basically no option to prevent it — short of deleting the `.pth` manually (there goes my automatic pip deployment!) and doing the import myself.

This is especially frustrating given the buggy state of some of the code. For example, it gives me no way to prevent psycopg2 patching (see #33) — by the time my code runs, it's too late to do anything.

Or it gives me no way to setup the config options or point your library to a different location. No, `agent-conf.json` it is, *in the current working directory* no less. Forget using standard Flask config files, for example, or having config compartmentalized in `instance` directories.

See [how New Relic does it](https://docs.newrelic.com/docs/agents/python-agent/installation-configuration/python-agent-integration) for a reference on much friendlier approach:

1. They have a launch script, yes.
2. But they also allow you to *not* use it and provide instructions on how to enable the agent in code.
3. They actually use WSGI middleware, which is by far the best way to plug things into WSGI apps.

**Comment by vaidy4github** [comment]
You might enable the instrumentation is code by importing librato_python_web.insturmentor, which is what the .pth file does. Agent-conf.json can specify a "libraries" option which you can use to disable psycopg2. There isn't a way to exclude a library yet, so you'll need to specify the ones you want. E.g.

{
   ...
   "libraries": ["flask", "logging", ...]
}

**Comment by vslavik** [comment]
> You might enable the instrumentation in code by importing librato_python_web.insturmentor, which is what the .pth file does

That's the point, I can't. It gets imported by the pth file, does nothing if the special environment variable is not set, and if I later import it as part of my WSGI launch script, it's a noop. I'd actually have to do this, which I *think* would work:
```python
from librato_python_web.instrumentor.bootstrap import init as librato_init
librato_init()
```

> agent-conf.json can specify a "libraries" option which you can use to disable psycopg2. 

Thanks!

**Comment by vaidy4github** [comment]
You are right, explicitly calling init() looks like it should address that particular issue.

**Comment by vaidy4github** [comment]
Master now has support for a new --config-path option which can be used with librato-launch, librato-config and librato-statsd-server to specify an alternate configuration file location.

**Comment by josephruscio** [comment]
@vslavik just wanted to pop in and thank you for filing these issues, they're definitely sparking a lot of discussion over here. We have some pretty sweet t-shirts, will reach out over email to try and send you one.
